"""Initial schema

Revision ID: 001
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Crear tabla tbl_perfil
    op.create_table('tbl_perfil',
        sa.Column('id_perfil', sa.Integer(), nullable=False),
        sa.Column('nombre', sa.String(length=255), nullable=True),
        sa.Column('descripcion', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id_perfil')
    )
    
    # Crear tabla tbl_iva
    op.create_table('tbl_iva',
        sa.Column('id_iva', sa.Integer(), nullable=False),
        sa.Column('porcentaje', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('descripcion', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id_iva')
    )
    
    # Crear tabla tbl_categoria
    op.create_table('tbl_categoria',
        sa.Column('id_categoria', sa.Integer(), nullable=False),
        sa.Column('nombre', sa.String(length=255), nullable=True),
        sa.Column('descripcion', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id_categoria')
    )
    
    # Crear tabla tbl_parametro
    op.create_table('tbl_parametro',
        sa.Column('id_parametro', sa.Integer(), nullable=False),
        sa.Column('descripcion', sa.String(length=255), nullable=True),
        sa.Column('valor', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id_parametro')
    )
    
    # Crear tabla tbl_persona
    op.create_table('tbl_persona',
        sa.Column('id_persona', sa.Integer(), nullable=False),
        sa.Column('tipo_identificacion', sa.String(length=255), nullable=True),
        sa.Column('identificacion', sa.String(length=255), nullable=True),
        sa.Column('genero', sa.String(length=255), nullable=True, comment='FEMENINO, MASCULINO'),
        sa.Column('nombre', sa.String(length=255), nullable=True),
        sa.Column('apellido', sa.String(length=255), nullable=True),
        sa.Column('direccion', sa.String(length=255), nullable=True),
        sa.Column('telefono', sa.String(length=255), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id_persona'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('identificacion'),
        sa.UniqueConstraint('tipo_identificacion', 'identificacion')
    )
    
    # Crear tabla tbl_subcategoria
    op.create_table('tbl_subcategoria',
        sa.Column('id_subcategoria', sa.Integer(), nullable=False),
        sa.Column('id_categoria', sa.Integer(), nullable=True),
        sa.Column('nombre', sa.String(length=255), nullable=True),
        sa.Column('descripcion', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id_subcategoria'),
        sa.ForeignKeyConstraint(['id_categoria'], ['tbl_categoria.id_categoria'], )
    )
    
    # Crear tabla tbl_usuario
    op.create_table('tbl_usuario',
        sa.Column('id_usuario', sa.Integer(), nullable=False),
        sa.Column('id_persona', sa.Integer(), nullable=True),
        sa.Column('id_perfil', sa.Integer(), nullable=True),
        sa.Column('username', sa.String(length=255), nullable=True),
        sa.Column('password', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id_usuario'),
        sa.UniqueConstraint('username'),
        sa.UniqueConstraint('id_persona', 'id_perfil'),
        sa.ForeignKeyConstraint(['id_persona'], ['tbl_persona.id_persona'], ),
        sa.ForeignKeyConstraint(['id_perfil'], ['tbl_perfil.id_perfil'], )
    )
    
    # Crear tabla tbl_producto
    op.create_table('tbl_producto',
        sa.Column('id_producto', sa.Integer(), nullable=False),
        sa.Column('id_categoria', sa.Integer(), nullable=True),
        sa.Column('id_subcategoria', sa.Integer(), nullable=True),
        sa.Column('id_iva', sa.Integer(), nullable=True),
        sa.Column('codigo', sa.String(length=255), nullable=True),
        sa.Column('marca', sa.String(length=255), nullable=True),
        sa.Column('nombre', sa.String(length=255), nullable=True),
        sa.Column('fecha_caducidad', sa.Date(), nullable=True),
        sa.Column('imagen', sa.String(length=255), nullable=True),
        sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('stock', sa.Integer(), nullable=True),
        sa.Column('estado', sa.String(length=255), nullable=True, default='ACTIVO'),
        sa.PrimaryKeyConstraint('id_producto'),
        sa.UniqueConstraint('codigo'),
        sa.ForeignKeyConstraint(['id_subcategoria'], ['tbl_subcategoria.id_subcategoria'], ),
        sa.ForeignKeyConstraint(['id_categoria'], ['tbl_categoria.id_categoria'], ),
        sa.ForeignKeyConstraint(['id_iva'], ['tbl_iva.id_iva'], )
    )
    
    # Crear tabla tbl_venta
    op.create_table('tbl_venta',
        sa.Column('id_venta', sa.Integer(), nullable=False),
        sa.Column('id_usuario', sa.Integer(), nullable=True),
        sa.Column('fecha_venta', sa.DateTime(), nullable=True, server_default=sa.text('(now())')),
        sa.Column('total_venta', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('estado', sa.String(length=255), nullable=True, default='PENDIENTE'),
        sa.PrimaryKeyConstraint('id_venta'),
        sa.ForeignKeyConstraint(['id_usuario'], ['tbl_usuario.id_usuario'], )
    )
    
    # Crear tabla tbl_carrito
    op.create_table('tbl_carrito',
        sa.Column('id_carrito', sa.Integer(), nullable=False),
        sa.Column('id_venta', sa.Integer(), nullable=True),
        sa.Column('id_usuario', sa.Integer(), nullable=True),
        sa.Column('id_producto', sa.Integer(), nullable=True),
        sa.Column('fecha_carrito', sa.DateTime(), nullable=True, server_default=sa.text('(now())')),
        sa.Column('cantidad', sa.Integer(), nullable=True),
        sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('iva_calculado', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('estado', sa.String(length=255), nullable=True, default='ACTIVO'),
        sa.Column('fecha_abandono', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id_carrito'),
        sa.ForeignKeyConstraint(['id_usuario'], ['tbl_usuario.id_usuario'], ),
        sa.ForeignKeyConstraint(['id_venta'], ['tbl_venta.id_venta'], ),
        sa.ForeignKeyConstraint(['id_producto'], ['tbl_producto.id_producto'], )
    )
    
    # Crear índices
    op.create_index('tbl_producto_index_2', 'tbl_producto', ['estado'])
    op.create_index('tbl_carrito_index_3', 'tbl_carrito', ['estado'])
    op.create_index('tbl_venta_index_4', 'tbl_venta', ['estado'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Eliminar índices
    op.drop_index('tbl_venta_index_4', table_name='tbl_venta')
    op.drop_index('tbl_carrito_index_3', table_name='tbl_carrito')
    op.drop_index('tbl_producto_index_2', table_name='tbl_producto')
    
    # Eliminar tablas en orden inverso
    op.drop_table('tbl_carrito')
    op.drop_table('tbl_venta')
    op.drop_table('tbl_producto')
    op.drop_table('tbl_usuario')
    op.drop_table('tbl_subcategoria')
    op.drop_table('tbl_persona')
    op.drop_table('tbl_parametro')
    op.drop_table('tbl_categoria')
    op.drop_table('tbl_iva')
    op.drop_table('tbl_perfil')
    
    # ### end Alembic commands ###
